spring.application.name=auction
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/auction}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:auction}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=true
spring.jpa.show-sql=false
spring.thymeleaf.cache=false
server.error.include-message=always
